# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xihua.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_xhu(object):
    def setupUi(self, xhu):
        xhu.setObjectName("xhu")
        xhu.resize(341, 290)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(xhu.sizePolicy().hasHeightForWidth())
        xhu.setSizePolicy(sizePolicy)
        xhu.setMinimumSize(QtCore.QSize(341, 290))
        xhu.setMaximumSize(QtCore.QSize(341, 290))
        xhu.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.label = QtWidgets.QLabel(xhu)
        self.label.setGeometry(QtCore.QRect(0, 0, 341, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(xhu)
        self.pushButton.setGeometry(QtCore.QRect(80, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(xhu)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(xhu)
        self.lineEdit.setGeometry(QtCore.QRect(80, 160, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(xhu)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 200, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(xhu)
        self.label_2.setGeometry(QtCore.QRect(10, 165, 54, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(xhu)
        self.label_3.setGeometry(QtCore.QRect(10, 206, 54, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(xhu)
        self.line.setGeometry(QtCore.QRect(0, 130, 341, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(xhu)
        QtCore.QMetaObject.connectSlotsByName(xhu)

    def retranslateUi(self, xhu):
        _translate = QtCore.QCoreApplication.translate
        xhu.setWindowTitle(_translate("xhu", "西华教务系统"))
        xhu.setWindowIcon(QtGui.QIcon('./images/index.png'))
        self.label.setText(_translate("xhu", "<html><head/><body><p><img src=\"./images/xhu.png\"/></p></body></html>"))
        self.pushButton.setText(_translate("xhu", "登录"))
        self.pushButton_2.setText(_translate("xhu", "退出"))
        self.lineEdit.setText(_translate("xhu", ""))
        self.lineEdit_2.setText(_translate("xhu", ""))
        self.label_2.setText(_translate("xhu", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt;\">学号</span></p></body></html>"))
        self.label_3.setText(_translate("xhu", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt;\">密码</span></p></body></html>"))
